// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vara.Api.Data;

#nullable disable

namespace Vara.Api.Data.Migrations
{
    [DbContext(typeof(VaraContext))]
    [Migration("20260227112725_Episode3")]
    partial class Episode3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vara.Api.Models.Entities.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short?>("CompetitionScore")
                        .HasColumnType("smallint")
                        .HasColumnName("competition_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KeywordIntent")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("keyword_intent");

                    b.Property<DateTime?>("LastAnalyzed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analyzed");

                    b.Property<string>("Niche")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("niche");

                    b.Property<short?>("SearchVolumeRelative")
                        .HasColumnType("smallint")
                        .HasColumnName("search_volume_relative");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keyword");

                    b.Property<string>("TrendDirection")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trend_direction");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TrendDirection")
                        .HasDatabaseName("idx_keywords_trend");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_keywords_user_id");

                    b.HasIndex("UserId", "Text", "Niche")
                        .IsUnique()
                        .HasDatabaseName("unique_user_keyword");

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("Vara.Api.Models.Entities.TrackedChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Handle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("handle");

                    b.Property<bool>("IsOwner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_owner");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<long?>("SubscriberCount")
                        .HasColumnType("bigint")
                        .HasColumnName("subscriber_count");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("thumbnail_url");

                    b.Property<long?>("TotalViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_view_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("VideoCount")
                        .HasColumnType("integer")
                        .HasColumnName("video_count");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("youtube_channel_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_tracked_channels_user_id");

                    b.HasIndex("UserId", "YoutubeChannelId")
                        .IsUnique()
                        .HasDatabaseName("unique_user_channel");

                    b.ToTable("tracked_channels", (string)null);
                });

            modelBuilder.Entity("Vara.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expires_at");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("free")
                        .HasColumnName("subscription_tier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("SubscriptionTier")
                        .HasDatabaseName("idx_users_subscription_tier");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Vara.Api.Models.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChannelId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("channel_name");

                    b.Property<int>("CommentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("comment_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("like_count");

                    b.Property<DateTime?>("MetadataFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metadata_fetched_at");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("text")
                        .HasColumnName("transcript_text");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("view_count");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("youtube_id");

                    b.HasKey("Id");

                    b.HasIndex("UploadDate")
                        .HasDatabaseName("idx_videos_upload_date");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_videos_user_id");

                    b.HasIndex("UserId", "YoutubeId")
                        .IsUnique()
                        .HasDatabaseName("unique_user_video");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("Vara.Api.Models.Entities.Keyword", b =>
                {
                    b.HasOne("Vara.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vara.Api.Models.Entities.TrackedChannel", b =>
                {
                    b.HasOne("Vara.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vara.Api.Models.Entities.Video", b =>
                {
                    b.HasOne("Vara.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
