FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /src

COPY ["Vara.Api.csproj", "."]
RUN dotnet restore

COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
